import logging
from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI
from typing import Literal
from pathlib import Path

from app.core.config import settings
from app.agents.state import RouteState

logger = logging.getLogger(__name__)

from app.agents.rag_agent import rag_agent_node
from app.agents.sql_agent import sql_agent_node
from app.agents.math_agent import math_agent_node

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROMPT_PATH = BASE_DIR / "prompts" / "route.txt"

with open(PROMPT_PATH, "r", encoding="utf-8") as f:
    PROMPT = f.read()

class SupervisorDecision(BaseModel):
    reasoning: str = Field(..., description="The reasoning behind the decision made by the supervisor.")
    next_action: Literal["sql_agent", "rag_agent", "math_agent", "end"] = Field(..., description="The next action to be taken by the supervisor.")
    draft_route: str = Field(..., description="The draft route generated by the supervisor.")
    intermediate_stop: str | None = Field(
        default=None,
        description=(
            "A real town/city to split the current leg at, when it is not feasible within "
            "max_driving_hours_per_day. Only set the first time a leg is found infeasible."
        )
    )

llm = ChatGoogleGenerativeAI(
    model="gemini-flash-lite-latest",
    google_api_key=settings.GEMINI_API_KEY,
    temperature=0.2,
    max_retries=3
)

structured_llm = llm.with_structured_output(SupervisorDecision)

def supervisor_node(state: RouteState):
    """
    Evaluates the current state and decides which agent goes next
    """
    state_as_text = str(state)

    response = structured_llm.invoke([
        ("system", PROMPT),
        ("human", state_as_text)
    ])

    next_action = response.next_action

    logger.debug(
        "supervisor_node: leg=%s->%s llm_next_action=%r poi_data=%s legal_context=%s "
        "fuel_cost=%s intermediate_stop=%r",
        state.get("origin"), state.get("destination"), next_action,
        bool(state.get("poi_data")), bool(state.get("legal_context")),
        state.get("fuel_cost"), response.intermediate_stop
    )

    if state.get("poi_data") and next_action == "sql_agent":
        next_action = "end"
    if state.get("legal_context") and next_action == "rag_agent":
        next_action = "end"
    if state.get("fuel_cost") and next_action == "math_agent":
        next_action = "end"

    # Hard invariant, enforced in Python: never let the LLM terminate a leg
    # with a required field still missing. The three guards above only stop
    # it from RE-visiting an already-satisfied step; nothing stopped it from
    # jumping straight to "end" while a step was never visited at all. This
    # is exactly what was happening: on multi-leg replans the state payload
    # sent to the model is larger (final_destination, itinerary_legs,
    # legal_context_by_region), and the model would sometimes emit "end"
    # for a leg whose legal_context was still "" — rag_agent_node was never
    # called for that leg, so legal_region stayed None. Same class of bug as
    # the earlier feasibility-hallucination fix: don't trust the LLM's "end"
    # signal for a hard invariant, verify it.
    if next_action == "end":
        if not state.get("poi_data"):
            logger.warning("supervisor_node: LLM said 'end' but poi_data is empty — forcing sql_agent")
            next_action = "sql_agent"
        elif not state.get("legal_context"):
            logger.warning("supervisor_node: LLM said 'end' but legal_context is empty — forcing rag_agent")
            next_action = "rag_agent"
        elif not state.get("fuel_cost"):
            logger.warning("supervisor_node: LLM said 'end' but fuel_cost is empty — forcing math_agent")
            next_action = "math_agent"

    # Everything below is a deterministic state machine over the LLM's "end" signal —
    # don't rely on the LLM to track multi-leg bookkeeping across calls (it was already
    # shown to ignore soft instructions under "produce a detailed itinerary" pressure).
    # math_analysis is the source of truth, not the prose in draft_route.
    math_analysis = state.get("math_analysis") or {}
    is_feasible = math_analysis.get("feasible_within_daily_limit", True)
    itinerary_legs = list(state.get("itinerary_legs") or [])
    final_destination = state.get("final_destination")

    if next_action != "end":
        return {"next_action": next_action}

    def _leg_summary():
        # Reference the region tag, not the full legal_context text — the text
        # itself lives once in final_itinerary.legal_context_by_region (Case 3).
        # Repeating a multi-hundred-word block per leg for a trip that revisits
        # the same region would inflate the response for no reason.
        return {
            "origin": state.get("origin"),
            "destination": state.get("destination"),
            "poi_data": state.get("poi_data"),
            "legal_region": state.get("legal_region"),
            "math_analysis": math_analysis
        }

    # Case 1: current leg is infeasible and we haven't split the trip yet — replan as
    # two legs instead of ending. Reuses sql/rag/math unchanged by repointing
    # origin/destination at the sub-leg and clearing the per-leg data so the routing
    # rules above naturally re-trigger sql_agent -> rag_agent -> math_agent for it.
    # Bounded to exactly one split (guarded by `not final_destination`) so a leg that
    # is STILL infeasible after splitting cannot trigger a second, unbounded split.
    if not is_feasible and not final_destination and response.intermediate_stop:
        return {
            "final_destination": state.get("destination"),
            "destination": response.intermediate_stop,
            "poi_data": [],
            "legal_context": "",
            "legal_region": None,
            "fuel_cost": 0.0,
            "math_analysis": {},
            "next_action": "sql_agent"
        }

    # Case 2: the first leg (origin -> intermediate stop) just finished — record it
    # and start the second leg (intermediate stop -> the real final destination).
    if final_destination and state.get("destination") != final_destination:
        itinerary_legs.append(_leg_summary())
        return {
            "itinerary_legs": itinerary_legs,
            "origin": state.get("destination"),
            "destination": final_destination,
            "poi_data": [],
            "legal_context": "",
            "legal_region": None,
            "fuel_cost": 0.0,
            "math_analysis": {},
            "next_action": "sql_agent"
        }

    # Case 3: the second leg just finished — assemble the combined multi-day itinerary.
    if final_destination and state.get("destination") == final_destination:
        itinerary_legs.append(_leg_summary())
        total_fuel_cost = sum(
            leg["math_analysis"].get("estimated_fuel_cost_eur", 0.0) for leg in itinerary_legs
        )
        all_feasible = all(
            leg["math_analysis"].get("feasible_within_daily_limit", True) for leg in itinerary_legs
        )
        final_itinerary = {
            "draft_route": response.draft_route,
            "feasible_within_daily_limit": all_feasible,
            "legs": itinerary_legs,
            "legal_context_by_region": state.get("legal_context_by_region") or {},
            "total_fuel_cost_eur": round(total_fuel_cost, 2)
        }
        if not all_feasible:
            final_itinerary["warning"] = (
                "One or more legs still exceed max_driving_hours_per_day even after "
                "splitting the route once; manual replanning is recommended."
            )
        return {
            "itinerary_legs": itinerary_legs,
            "final_itinerary": final_itinerary,
            "next_action": "end"
        }

    # Case 4: normal single-leg completion (feasible), or infeasible with no split
    # available (already split once, or the LLM didn't propose an intermediate_stop).
    final_itinerary = {
        "draft_route": response.draft_route,
        "feasible_within_daily_limit": is_feasible
    }
    if not is_feasible:
        final_itinerary["warning"] = (
            f"Estimated driving time ({math_analysis.get('driving_time_hours')}h) exceeds "
            f"max_driving_hours_per_day ({state.get('max_driving_hours_per_day')}h) and no "
            "further automatic split was made. Manual replanning is recommended."
        )

    return {
        "final_itinerary": final_itinerary,
        "next_action": "end"
    }