from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI
from typing import Literal
from pathlib import Path

from app.core.config import settings
from app.agents.state import RouteState

from app.agents.rag_agent import rag_agent_node
from app.agents.sql_agent import sql_agent_node
from app.agents.math_agent import math_agent_node

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROMPT_PATH = BASE_DIR / "prompts" / "route.txt"

with open(PROMPT_PATH, "r", encoding="utf-8") as f:
    PROMPT = f.read()

class SupervisorDecision(BaseModel):
    reasoning: str = Field(..., description="The reasoning behind the decision made by the supervisor.")
    next_action: Literal["sql_agent", "rag_agent", "math_agent", "end"] = Field(..., description="The next action to be taken by the supervisor.")
    draft_route: str = Field(..., description="The draft route generated by the supervisor.")

llm = ChatGoogleGenerativeAI(
    model="gemini-flash-lite-latest",
    google_api_key=settings.GEMINI_API_KEY,
    temperature=0.2,
    max_retries=3
)

structured_llm = llm.with_structured_output(SupervisorDecision)

def supervisor_node(state: RouteState):
    """
    Evaluates the current state and decides which agent goes next
    """
    state_as_text = str(state)

    response = structured_llm.invoke([
        ("system", PROMPT),
        ("human", state_as_text)
    ])

    next_action = response.next_action

    if state.get("poi_data") and next_action == "sql_agent":
        next_action = "end"
    if state.get("legal_context") and next_action == "rag_agent":
        next_action = "end"
    if state.get("fuel_cost") and next_action == "math_agent":
        next_action = "end"

    return {
        "final_itinerary": {"draft_route": response.draft_route},
        "next_action": next_action
    }