import logging
from pydantic import BaseModel, Field
from langchain_google_genai import ChatGoogleGenerativeAI
from typing import Literal
from pathlib import Path

from app.core.config import settings
from app.agents.state import RouteState

logger = logging.getLogger(__name__)

from app.agents.rag_agent import rag_agent_node
from app.agents.sql_agent import sql_agent_node
from app.agents.math_agent import math_agent_node

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROMPT_PATH = BASE_DIR / "prompts" / "route.txt"

with open(PROMPT_PATH, "r", encoding="utf-8") as f:
    PROMPT = f.read()

class SupervisorDecision(BaseModel):
    reasoning: str = Field(..., description="The reasoning behind the decision made by the supervisor.")
    next_action: Literal["sql_agent", "rag_agent", "math_agent", "end"] = Field(..., description="The next action to be taken by the supervisor.")
    draft_route: str = Field(..., description="The draft route generated by the supervisor.")
    intermediate_stop: str | None = Field(
        default=None,
        description=(
            "A real town/city to split the current leg at, when it is not feasible within "
            "max_driving_hours_per_day. Set it every time the current leg is infeasible, "
            "even if a previous leg was already split — pick the farthest reachable point, "
            "not just any reachable point, to minimize how many splits are needed."
        )
    )

llm = ChatGoogleGenerativeAI(
    model="gemini-flash-lite-latest",
    google_api_key=settings.GEMINI_API_KEY,
    temperature=0.2,
    max_retries=3
)

structured_llm = llm.with_structured_output(SupervisorDecision)

def supervisor_node(state: RouteState):
    """
    Evaluates the current state and decides which agent goes next
    """
    state_as_text = str(state)

    response = structured_llm.invoke([
        ("system", PROMPT),
        ("human", state_as_text)
    ])

    next_action = response.next_action

    logger.debug(
        "supervisor_node: leg=%s->%s llm_next_action=%r poi_data=%s legal_context=%s "
        "fuel_cost=%s intermediate_stop=%r",
        state.get("origin"), state.get("destination"), next_action,
        bool(state.get("poi_data")), bool(state.get("legal_context")),
        state.get("fuel_cost"), response.intermediate_stop
    )

    if state.get("poi_data") and next_action == "sql_agent":
        next_action = "end"
    if state.get("legal_context") and next_action == "rag_agent":
        next_action = "end"
    if state.get("fuel_cost") and next_action == "math_agent":
        next_action = "end"

    # Hard invariant, enforced in Python: never let the LLM terminate a leg
    # with a required field still missing. The three guards above only stop
    # it from RE-visiting an already-satisfied step; nothing stopped it from
    # jumping straight to "end" while a step was never visited at all. This
    # is exactly what was happening: on multi-leg replans the state payload
    # sent to the model is larger (final_destination, itinerary_legs,
    # legal_context_by_region), and the model would sometimes emit "end"
    # for a leg whose legal_context was still "" — rag_agent_node was never
    # called for that leg, so legal_region stayed None. Same class of bug as
    # the earlier feasibility-hallucination fix: don't trust the LLM's "end"
    # signal for a hard invariant, verify it.
    if next_action == "end":
        if not state.get("poi_data"):
            logger.warning("supervisor_node: LLM said 'end' but poi_data is empty — forcing sql_agent")
            next_action = "sql_agent"
        elif not state.get("legal_context"):
            logger.warning("supervisor_node: LLM said 'end' but legal_context is empty — forcing rag_agent")
            next_action = "rag_agent"
        elif not state.get("fuel_cost"):
            logger.warning("supervisor_node: LLM said 'end' but fuel_cost is empty — forcing math_agent")
            next_action = "math_agent"

    # Everything below is a deterministic state machine over the LLM's "end" signal —
    # don't rely on the LLM to track multi-leg bookkeeping across calls (it was already
    # shown to ignore soft instructions under "produce a detailed itinerary" pressure).
    # math_analysis is the source of truth, not the prose in draft_route.
    math_analysis = state.get("math_analysis") or {}
    is_feasible = math_analysis.get("feasible_within_daily_limit", True)
    itinerary_legs = list(state.get("itinerary_legs") or [])
    final_destination = state.get("final_destination")
    split_count = state.get("split_count", 0)

    if next_action != "end":
        return {"next_action": next_action}

    def _leg_summary():
        # Reference the region tag, not the full legal_context text — the text
        # itself lives once in final_itinerary.legal_context_by_region (Case 3).
        # Repeating a multi-hundred-word block per leg for a trip that revisits
        # the same region would inflate the response for no reason.
        return {
            "origin": state.get("origin"),
            "destination": state.get("destination"),
            "poi_data": state.get("poi_data"),
            "legal_region": state.get("legal_region"),
            "math_analysis": math_analysis
        }

    # Bounds how many times a single request can split. Not "exactly one
    # split": a route can need a second split if the LLM's chosen
    # intermediate_stop was a poor midpoint and the REMAINING leg is still
    # infeasible (observed directly: Barcelona->Málaga split via Valencia
    # left a 6.82h Valencia->Málaga leg against a 6h limit — the prompt only
    # required the stop be reachable FROM origin, never that the remainder
    # also fit). Bounding by leg count (not "has this leg been split
    # before") is what lets the same infeasible-leg check apply uniformly
    # whether this is the very first attempt or a leg produced by an earlier
    # split, without special-casing "first split" vs "second split".
    #
    # Bounded by `split_count`, NOT `len(itinerary_legs)`: a leg only gets
    # appended to itinerary_legs once it's finished and we move past it, but
    # if the LLM keeps proposing an intermediate_stop that's ALSO infeasible,
    # we re-split the same not-yet-finished leg over and over — itinerary_legs
    # never grows in that scenario, so bounding on its length would never
    # trigger and this would loop forever (caught by testing before this
    # ever ran against the real API).
    MAX_LEGS = 4

    # Is the CURRENT leg the one that reaches the user's real final
    # destination? True both for a trip that was never split (final_destination
    # is None) and for whichever leg's destination equals it once set.
    is_final_leg = not final_destination or state.get("destination") == final_destination

    # Split (or re-split) this leg: applies equally to the original whole-trip
    # attempt and to any leg produced by a previous split. Reuses sql/rag/math
    # unchanged by repointing `destination` at the sub-leg and clearing the
    # per-leg data so the routing rules above naturally re-trigger
    # sql_agent -> rag_agent -> math_agent for it. `origin` is left as-is —
    # we're shortening THIS leg's far end, not moving its start.
    if not is_feasible and split_count < MAX_LEGS - 1 and response.intermediate_stop:
        return {
            "final_destination": final_destination or state.get("destination"),
            "destination": response.intermediate_stop,
            "poi_data": [],
            "legal_context": "",
            "legal_region": None,
            "fuel_cost": 0.0,
            "math_analysis": {},
            "split_count": split_count + 1,
            "next_action": "sql_agent"
        }

    # This leg reached an intermediate stop, not the real final destination —
    # record it and continue from there toward final_destination. Whether
    # THIS leg turned out feasible or we simply ran out of split budget for
    # it (handled by the aggregate feasibility check below), we always move
    # on rather than looping on the same leg forever.
    if not is_final_leg:
        itinerary_legs.append(_leg_summary())
        return {
            "itinerary_legs": itinerary_legs,
            "origin": state.get("destination"),
            "destination": final_destination,
            "poi_data": [],
            "legal_context": "",
            "legal_region": None,
            "fuel_cost": 0.0,
            "math_analysis": {},
            "next_action": "sql_agent"
        }

    # This leg reaches the real final destination and is either feasible, or
    # we've exhausted the split budget and must report honestly instead of
    # looping forever.
    if final_destination is None:
        # Never split at all — plain single-leg result.
        final_itinerary = {
            "draft_route": response.draft_route,
            "feasible_within_daily_limit": is_feasible
        }
        if not is_feasible:
            final_itinerary["warning"] = (
                f"Estimated driving time ({math_analysis.get('driving_time_hours')}h) exceeds "
                f"max_driving_hours_per_day ({state.get('max_driving_hours_per_day')}h) and no "
                "further automatic split was made. Manual replanning is recommended."
            )
        return {
            "final_itinerary": final_itinerary,
            "next_action": "end"
        }

    # Multi-leg trip: assemble the combined itinerary from every leg recorded
    # along the way.
    itinerary_legs.append(_leg_summary())
    total_fuel_cost = sum(
        leg["math_analysis"].get("estimated_fuel_cost_eur", 0.0) for leg in itinerary_legs
    )
    all_feasible = all(
        leg["math_analysis"].get("feasible_within_daily_limit", True) for leg in itinerary_legs
    )
    final_itinerary = {
        "draft_route": response.draft_route,
        "feasible_within_daily_limit": all_feasible,
        "legs": itinerary_legs,
        "legal_context_by_region": state.get("legal_context_by_region") or {},
        "total_fuel_cost_eur": round(total_fuel_cost, 2)
    }
    if not all_feasible:
        final_itinerary["warning"] = (
            f"One or more legs still exceed max_driving_hours_per_day even after "
            f"splitting into {len(itinerary_legs)} legs (limit: {MAX_LEGS} legs per "
            "request); manual replanning is recommended."
        )
    return {
        "itinerary_legs": itinerary_legs,
        "final_itinerary": final_itinerary,
        "next_action": "end"
    }